# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2817godsrro_xzOKtP6hSpenD5H7wvO
"""

import  numpy as  np
import  pandas  as  pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('placement.csv')

df.shape

plt.figure(figsize=(16,5))
plt.subplot(1,2,1)
sns.distplot(df['cgpa'])
plt.subplot(1,2,2)
sns.distplot(df['placement_exam_marks'])
plt.show()





print("Mean value of cgpa", df['cgpa'].mean())

print("Std value of cgpa", df['cgpa'].std())

print("Min value of cgpa", df['cgpa'].min())

print("Max value of cgpa",df['cgpa'].max())

print("Mean value of cgpa", df['cgpa'].mean())

print("Std value of cgpa", df['cgpa'].std())

print("Min value of cgpa", df['cgpa'].min())

print("Max value of cgpa",df['cgpa'].max())

print("Highest allowed", df['cgpa'].mean() + 3*df['cgpa'].std())

print("Lowest allowed", df['cgpa'].mean() -

3*df['cgpa'].std())

df[(df['cgpa']>8.80)|(df['cgpa']<5.11)]

new_df = df[(df['cgpa'] < 8.80) & (df['cgpa'] > 5.11)]
new_df

import  numpy as  np
import  pandas  as  pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_cvs('placement.cvs')